version: '3'

services:
  smtp:
    image: tianon/exim4
    ports:
      - 25:25
    networks:
      - scratchpads
  apache:
    image: naturalhistorymuseum/scratchpad
    ports:
      - 80:80
    networks:
      - scratchpads
    volumes:
      - site-files:/app/sites/default
      # Import an existing site:
      # - ./mysite.example.com:/app/sites/mysite.example.com
    environment:
      # Site settings:
      # - BASE_URL=http://mysite.example.com
      # - SERVER_NAME=mysite.example.com
      # Pass the password from the .env file:
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
  db:
    image: naturalhistorymuseum/scratchpad-mysql
    expose:
     - 3306
    networks:
     - scratchpads
    volumes:
     - site-data:/var/lib/mysql
     # Import an existing database:
     # - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      # Pass the password from the .env file:
      - MYSQL_ROOT_PASSWORD:${MYSQL_PASSWORD}
  solr:
    image: naturalhistorymuseum/scratchpad-solr
    expose:
      - 8983
    volumes:
      - solr-data:/etc/opt/solr/scratchpads2/data
    networks:
      - scratchpads

volumes:
  site-files:
  site-data:

networks:
  scratchpads: