version: '2.3'

services:
  smtp:
    image: tianon/exim4
    ports:
      - 25:25
    networks:
      - sp_drupal
  apache:
    image: sp2
    volumes:
      - ./apache/settings.php:/app/sites/default/settings.php
    environment:
      MYSQL_PASSWORD: platypodes
      MYSQL_DATABASE: sp2
      MYSQL_USER: root
      MYSQL_HOST: db
      SOLR_HOSTNAME: solr
      SOLR_CORE: scratchpads2
    ports:
      - 8080:80
    networks:
      - sp_drupal

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: platypodes
      MYSQL_DATABASE: sp2
    ports:
     - 3306:3306
    networks:
     - sp_drupal
    volumes:
     - ./mysql:/etc/mysql/conf.d
     - sp_data:/var/lib/mysql

  solr:
    image: sp2-solr
    ports:
      - 8983:8983
    volumes:
      - solr-data:/etc/opt/solr/scratchpads2/data
    networks:
      - sp_drupal

volumes:
  sp_data:
  solr-data:

networks:
  sp_drupal:
    ipam:
      config:
        - gateway: 172.20.0.1
          subnet: 172.20.0.0/24