version: '3'

services:
  smtp:
    image: tianon/exim4
    ports:
      - 25:25
    networks:
      - sp_drupal
  apache:
    image: sp2
    volumes:
      - ./apache/settings.php:/app/sites/default/settings.php
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-platypodes}
      MYSQL_DATABASE: sp2
      MYSQL_USER: root
      MYSQL_HOST: db
      SOLR_HOSTNAME: solr
      SOLR_CORE: scratchpads2
      BASE_URL: http://localhost:${PORT:-80}
    ports:
      - ${PORT:-80}:80
    networks:
      - sp_drupal

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-platypodes}
      MYSQL_DATABASE: sp2
    expose:
     - 3306
    networks:
     - sp_drupal
    volumes:
     - ./mysql:/etc/mysql/conf.d
     - sp_data:/var/lib/mysql

  solr:
    image: sp2-solr
    expose:
      - 8983
    volumes:
      - solr-data:/etc/opt/solr/scratchpads2/data
    networks:
      - sp_drupal

volumes:
  sp_data:
  solr-data:

networks:
  sp_drupal: