version: '3.1'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: platypodes
      MYSQL_DATABASE: sp2
    ports:
     - 3306:3306
    networks:
     - drupal
    volumes:
     - ./data:/var/lib/mysql

  sp2:
    image: sp2
    environment:
      MYSQL_PASSWORD: platypodes
      MYSQL_DATABASE: sp2
      MYSQL_USER: root
      MYSQL_HOST: db
    ports:
      - 8080:80
    networks:
      - drupal
networks:
  drupal: